logging.level: 
  root: INFO

spring:
  application.name: car-application
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/liquibase-changeLog.xml
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

endpoints.enabled: true

logging:
  level:
    org:
      springframework:
        cache: TRACE
      hibernate:
        orm:
          jdbc:
            bind: TRACE

server.port: 3000
server:
  servlet:
    context-path : /cars-api/v1
